[build]
environment = { PHP_VERSION = "7.4" }
publish = "/build_production"
command = "npm run production"

[context.deploy-preview]
publish = "/build_staging"
command = "npm run staging"

[[redirects]]
from = "/docs/master/*"
to = "/docs/v3/:splat"
status = 302
